In [1]:
import pandas as pd

url = "https://raw.githubusercontent.com/nkmwicz/data-for-students/refs/heads/main/soccer-players.csv"

df = pd.read_csv(url)
df.head()

,player_id,first_name,last_name,name,last_season,current_club_id,player_code,country_of_birth,city_of_birth,country_of_citizenship,...,foot,height_in_cm,contract_expiration_date,agent_name,image_url,url,current_club_domestic_competition_id,current_club_name,market_value_in_eur,highest_market_value_in_eur
0,10,Miroslav,Klose,Miroslav Klose,2015,398,miroslav-klose,Poland,Opole,Germany,...,right,184.0,NaN,ASBW Sport Marketing,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/miroslav-klose...,IT1,Società Sportiva Lazio S.p.A.,1000000.0,30000000.0
1,26,Roman,Weidenfeller,Roman Weidenfeller,2017,16,roman-weidenfeller,Germany,Diez,Germany,...,left,190.0,NaN,Neubauer 13 GmbH,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/roman-weidenfe...,L1,Borussia Dortmund,750000.0,8000000.0
2,65,Dimitar,Berbatov,Dimitar Berbatov,2015,1091,dimitar-berbatov,Bulgaria,Blagoevgrad,Bulgaria,...,NaN,NaN,NaN,CSKA-AS-23 Ltd.,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/dimitar-berbat...,GR1,Panthessalonikios Athlitikos Omilos Konstantin...,1000000.0,34500000.0
3,77,NaN,Lúcio,Lúcio,2012,506,lucio,Brazil,Brasília,Brazil,...,NaN,NaN,NaN,NaN,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/lucio/profil/s...,IT1,Juventus Football Club,200000.0,24500000.0
4,80,Tom,Starke,Tom Starke,2017,27,tom-starke,East Germany (GDR),Freital,Germany,...,right,194.0,NaN,IFM,https://img.a.transfermarkt.technology/portrai...,https://www.transfermarkt.co.uk/tom-starke/pro...,L1,FC Bayern München,100000.0,3000000.0

In [2]:
from functions.convertion_cm_to_inches import convert_height

df["height_in_inches"] = df["height_in_cm"].apply(convert_height)
df["height_in_inches"]

0        6.036749
1        6.233599
2             NaN
3             NaN
4        6.364833
           ...
32398    5.839898
32399    5.905515
32400    5.380580
32401         NaN
32402         NaN
Name: height_in_inches, Length: 32403, dtype: float64

In [3]:
df.loc[df["current_club_domestic_competition_id"]=="SA1"]

Empty DataFrame
Columns: [player_id, first_name, last_name, name, last_season, current_club_id, player_code, country_of_birth, city_of_birth, country_of_citizenship, date_of_birth, sub_position, position, foot, height_in_cm, contract_expiration_date, agent_name, image_url, url, current_club_domestic_competition_id, current_club_name, market_value_in_eur, highest_market_value_in_eur, height_in_inches]
Index: []

[0 rows x 24 columns]

In [4]:
df.describe()

,player_id,last_season,current_club_id,height_in_cm,market_value_in_eur,highest_market_value_in_eur,height_in_inches
count,3.240300e+04,32403.000000,32403.000000,30059.000000,3.086900e+04,3.086900e+04,30059.000000
mean,3.445789e+05,2019.337777,4809.252045,182.291161,1.611350e+06,3.675045e+06,5.980684
std,2.806831e+05,3.965914,11601.982978,6.971224,6.362017e+06,9.653897e+06,0.228715
min,1.000000e+01,2012.000000,3.000000,17.000000,1.000000e+04,1.000000e+04,0.557743
25%,1.066980e+05,2016.000000,403.000000,178.000000,1.000000e+05,2.750000e+05,5.839898
50%,2.824210e+05,2020.000000,1071.000000,183.000000,2.500000e+05,8.000000e+05,6.003940
75%,5.242085e+05,2023.000000,3060.000000,187.000000,7.000000e+05,2.800000e+06,6.135174
max,1.309800e+06,2024.000000,110302.000000,207.000000,2.000000e+08,2.000000e+08,6.791342

In [5]:
df["height_in_cm"].mean()

np.float64(182.29116071725608)

In [6]:
df["height_in_inches"].mean()

np.float64(5.980684355462036)

In [7]:
df["height_in_cm"].median()

183.0

In [8]:
df["height_in_cm"].quantile(.75)

np.float64(187.0)

In [9]:
df["height_in_cm"].skew()

np.float64(-1.7751475048518246)

In [10]:
from scipy import stats

stats.skew(df["height_in_cm"], nan_policy="omit")

np.float64(-1.7750589204621978)

In [11]:
df["height_in_cm"].kurt()

np.float64(40.3723954752419)

In [12]:
stats.kurtosis(df["height_in_cm"].dropna())

np.float64(40.36548066183285)

In [13]:
print(f"{'='*5}DF Shape: {df.shape} {'='*5}")
num_cols = []
cat_cols = []
for col in df.columns:
    if pd.api.types.is_numeric_dtype(df[col]):
        num_cols.append(col)
    else:
        cat_cols.append(col)    
print(f"Numeric columns: {num_cols}")
print(f"Categorical columns: {cat_cols}")

=====DF Shape: (32403, 24) =====
Numeric columns: ['player_id', 'last_season', 'current_club_id', 'height_in_cm', 'market_value_in_eur', 'highest_market_value_in_eur', 'height_in_inches']
Categorical columns: ['first_name', 'last_name', 'name', 'player_code', 'country_of_birth', 'city_of_birth', 'country_of_citizenship', 'date_of_birth', 'sub_position', 'position', 'foot', 'contract_expiration_date', 'agent_name', 'image_url', 'url', 'current_club_domestic_competition_id', 'current_club_name']

In [14]:
print(f"{'*'*3}Numeric Cols{'*'*3}")
for col in num_cols:
    print(col)
    print(f"\tMin: {df[col].min()}")
    print(f"\tMax: {df[col].max()}")

***Numeric Cols***
player_id
	Min: 10
	Max: 1309800
last_season
	Min: 2012
	Max: 2024
current_club_id
	Min: 3
	Max: 110302
height_in_cm
	Min: 17.0
	Max: 207.0
market_value_in_eur
	Min: 10000.0
	Max: 200000000.0
highest_market_value_in_eur
	Min: 10000.0
	Max: 200000000.0
height_in_inches
	Min: 0.5577430833333333
	Max: 6.7913422500000005

In [15]:
from functions.eda import eda

eda(df)

=====DF Shape: (32403, 24) =====
***Numeric Cols***
player_id
	Num_NA:0
	% NA: 0.0%
	Min: 10
	Max: 1309800
	Range: 1309790
	Q1:106698.0
	Q3:524208.5
	 SD:280683.13989913743
last_season
	Num_NA:0
	% NA: 0.0%
	Min: 2012
	Max: 2024
	Range: 12
	Q1:2016.0
	Q3:2023.0
	 SD:3.965914065614276
current_club_id
	Num_NA:0
	% NA: 0.0%
	Min: 3
	Max: 110302
	Range: 110299
	Q1:403.0
	Q3:3060.0
	 SD:11601.982977954987
height_in_cm
	Num_NA:2344
	% NA: 7.233898095855322%
	Min: 17.0
	Max: 207.0
	Range: 190.0
	Q1:178.0
	Q3:187.0
	 SD:6.971224376399549
market_value_in_eur
	Num_NA:1534
	% NA: 4.734129555905318%
	Min: 10000.0
	Max: 200000000.0
	Range: 199990000.0
	Q1:100000.0
	Q3:700000.0
	 SD:6362017.247132119
highest_market_value_in_eur
	Num_NA:1534
	% NA: 4.734129555905318%
	Min: 10000.0
	Max: 200000000.0
	Range: 199990000.0
	Q1:275000.0
	Q3:2800000.0
	 SD:9653897.3865907
height_in_inches
	Num_NA:2344
	% NA: 7.233898095855322%
	Min: 0.5577430833333333
	Max: 6.7913422500000005
	Range: 6.233599166666667
	Q1:5.839898166666667
	Q3:6.135173916666667
	 SD:0.22871483401772097


***Categorical Cols***
first_name
	Num NA: 2058
	% NA: 6.351263771872976%
	 Num Uniques: 6966
last_name
	Num NA: 0
	% NA: 0.0%
	 Num Uniques: 23701
name
	Num NA: 0
	% NA: 0.0%
	 Num Uniques: 31708
player_code
	Num NA: 0
	% NA: 0.0%
	 Num Uniques: 31667
country_of_birth
	Num NA: 2803
	% NA: 8.650433601826991%
	 Num Uniques: 185
city_of_birth
	Num NA: 2461
	% NA: 7.5949757738481%
	 Num Uniques: 8537
country_of_citizenship
	Num NA: 380
	% NA: 1.1727309199765454%
	 Num Uniques: 183
date_of_birth
	Num NA: 47
	% NA: 0.14504829799709903%
	 Num Uniques: 9272
sub_position
	Num NA: 185
	% NA: 0.5709347899885814%
	 Num Uniques: 13
position
	Num NA: 0
	% NA: 0.0%
	 Num Uniques: 5
Unique Values:['Attack' 'Goalkeeper' 'Defender' 'Midfield' 'Missing']
foot
	Num NA: 2593
	% NA: 8.002345461839953%
	 Num Uniques: 3
Unique Values:['right' 'left' nan 'both']
contract_expiration_date
	Num NA: 12131
	% NA: 37.43789155325124%
	 Num Uniques: 114
agent_name
	Num NA: 16015
	% NA: 49.424436009011515%
	 Num Uniques: 2833
image_url
	Num NA: 0
	% NA: 0.0%
	 Num Uniques: 26561
url
	Num NA: 0
	% NA: 0.0%
	 Num Uniques: 32403
current_club_domestic_competition_id
	Num NA: 0
	% NA: 0.0%
	 Num Uniques: 14
current_club_name
	Num NA: 0
	% NA: 0.0%
	 Num Uniques: 437